fix(network_random_interruptions): query time range too narrow
fixes:
 File /sct/sdcm/nemesis.py, line 1473, in disrupt_network_random_interruptions

    avg_bitrate_per_node = max([float(avg_rate) for _, avg_rate in results[0][values]])

IndexError: list index out of range
(cherry picked from commit 0b9673d9a913a39c6376cb3b3eda0c04b717dbcc)